stages:
  prepare:
    cmd: python src/tokenize_and_sample.py -i dataset/raw_tickets.csv -o 
      dataset/sample_tickets.json
    deps:
    - dataset/raw_tickets.csv
    - src/tokenize_and_sample.py
    outs:
    - dataset/sample_tickets.json
